language: python
services:
  - docker
before_install:
  - |
    if [ ! -z "$encrypted_103700d0e85f_key" ]; then
      openssl aes-256-cbc -K $encrypted_103700d0e85f_key -iv $encrypted_103700d0e85f_iv -in scripts/launchpad-secret.key.enc -out scripts/launchpad-secret.key -d
      openssl aes-256-cbc -K $encrypted_103700d0e85f_key -iv $encrypted_103700d0e85f_iv -in scripts/launchpad-public.key.enc -out scripts/launchpad-public.key -d
      openssl aes-256-cbc -K $encrypted_103700d0e85f_key -iv $encrypted_103700d0e85f_iv -in scripts/launchpad.ssh.tar.enc -out scripts/launchpad.ssh.tar -d
      openssl aes-256-cbc -K $encrypted_103700d0e85f_key -iv $encrypted_103700d0e85f_iv -in scripts/aur_key.enc -out scripts/aur_key -d
    fi
  - source ./scripts/common.sh
  - docker pull $BUILD_IMAGE
install:
  # this is to skip default "pip install -r requirements.txt" on travis
  - true
script:
  - if [ ! -z "$TRAVIS_TAG" ] && [ ! -z "$encrypted_103700d0e85f_key" ]; then ./ul build-release $TRAVIS_TAG; fi
branches:
  only:
  - master
  - dev
  - python3
  - "/^\\d+.\\d+.\\d+/"
deploy:
  provider: releases
  draft: true
  name: $TRAVIS_TAG
  api_key:
    secure: fnFAWAF1ODSD46U5G0zUPGZRQmOBm7yaVjUlC4SOvuI9rElYho5Xmej4gkbhYYawQbc0o+My8HZF2v2G8ApGOnInFX3Mqx3ms7gG+gUojeV3914k71C5li7c/hNpq0XjFGPL4hAVGE8Qn/YTnYo5r+B5TmJeSVUmL4K5aVIhFgXmiEzY6UQzBosUapJzb7VmQwbND/TwgInjhK98dXnXEwRoKN+eTaTjfEUJ7zavIk+VftiB7UaMeOZRbBNfCK5GEAaFdOI/m0ii7v0b5GVPSkvMP1fEjxIlvk/Q///Mxxy4FcGn5f4+8k/0ls3RjnSFct9SgZVd6rmhS21GV1S8+5m+C04ZCtkDnn8DIFaDJ75Pi78sZrSZ8Zv/KC8u+3rdsogsOdulhTdKNMejQozS6vnZ1jQfuLITR1klnKm3SLGD5hGIxoOe1Ym3QA54ixQf6GFbHkUSfJLPM7IVw4mjHBRk+PJlG1AEgdLmDW02skfB3ZWpfbymrtMcpqORFHuXCEm6WmaWschYgIY4VyT1LfzV+ZdAzvO5T74GHQlG6c1Wk0HBw2tE830lgHvNAi2sTkcYaG61m+UiLSMsbsAxD5oLi2D9EEZmDrdmb18wcz9k18knFoXdMmcBzsxCCWrswPzg2ybAawW6IKm0+LC4H1X7lHcXD07hJpxaOfQVmoM=
  file:
    - ulauncher_${TRAVIS_TAG}.tar.gz
    - ulauncher_${TRAVIS_TAG}_all.deb
  skip_cleanup: true
  on:
    repo: Ulauncher/Ulauncher
    tags: true
    overwrite: true
