language: python
services:
  - docker
before_install:
  - |
    if [ ! -z "$encrypted_103700d0e85f_key" ]; then
      openssl aes-256-cbc -K $encrypted_103700d0e85f_key -iv $encrypted_103700d0e85f_iv -in scripts/launchpad-secret.key.enc -out scripts/launchpad-secret.key -d
      openssl aes-256-cbc -K $encrypted_103700d0e85f_key -iv $encrypted_103700d0e85f_iv -in scripts/launchpad-public.key.enc -out scripts/launchpad-public.key -d
      openssl aes-256-cbc -K $encrypted_103700d0e85f_key -iv $encrypted_103700d0e85f_iv -in scripts/launchpad.ssh.tar.enc -out scripts/launchpad.ssh.tar -d
      openssl aes-256-cbc -K $encrypted_103700d0e85f_key -iv $encrypted_103700d0e85f_iv -in scripts/aur_key.enc -out scripts/aur_key -d
    fi
  - source ./scripts/common.sh
  - docker pull $BUILD_IMAGE
install:
  # this is to skip default "pip install -r requirements.txt" on travis
  - true
script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ -z "$TRAVIS_TAG" ]; then ./ul run-ci; fi
  - if [ ! -z "$TRAVIS_TAG" ] && [ ! -z "$encrypted_103700d0e85f_key" ]; then ./ul make-release $TRAVIS_TAG; fi
  - export APP_VERSION=$(echo "$TRAVIS_TAG" | sed 's/-beta/~beta/')
branches:
  only:
  - master
  - dev
  - python3
  - "/^\\d+.\\d+.\\d+/"
deploy:
  provider: releases
  api_key:
    secure: EG0AuBGirBDu5XYKFZwITcXq/0U50f2PR5UVhbspr6D8LLcLbuxItMVnNjSuT1BQNpt7ijJ3gQfkh0QXZdv02d/H0l0+U2YCCyytvypMeqSfVawIGxYvYK2i5DH+0k7rVC9WoimpB+4lNx+VZILwzjudCzzefH8+ZSPPoeFOPYC8SU/VYPx2K31jgz7LlTWiEsijPF8XErXmHdQ3IDnDFnNZpNVnWPlArozQkqsJF9tosBPO72ZLFKLpAH+Eg+WVnPmqQlzH6MIzE9bsyxDD98mRvhkBNUI8EJI/qPqLczA9wJVt33VJrnQhJP5QEhNZ4IwyHuK61oUqM6/Q80LJhFpxeNebnkGIYWrkmY8pKJAV/BnIU8ejiVrMxqLzq+plb1Bzz08NLSyD9xp0o4KHDuMC/e6dohuNFaSlOCHv41Z9bQrGBXnQRjG4b4vN1cAK8ozVVLO2hosWf1vj0ItUPzZG4X1psjspbEcWlDyPak6ZUYoVsT9/xsGojN7N6MPqXxnrkzn+ffHL/gzdE6nIxwQNeg42xrRfepvO+96G4c53gF/YEMLYccKarfriLmrpRd+OzYx2Dbc8K2AMhXE5gseswQmHeSJj0ln0Kd1XKBEGqYlwtha3ZzRvOR00I9ONhAZL2fasX/H19nL9odH5NsdVjzxv9vuA2Q2KiA/meZc=
  file:
    - ulauncher_${APP_VERSION}.tar.gz
    - ulauncher_${APP_VERSION}_all.deb
    - ulauncher_${APP_VERSION}_fedora.rpm
  skip_cleanup: true
  on:
    repo: Ulauncher/Ulauncher
    tags: true
    overwrite: true
