blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url: https://github.com/Ulauncher/Ulauncher/discussions/991
    about: Common issues and how to work around them.
  - name: Ulauncher Discussions
    url: https://github.com/Ulauncher/Ulauncher/discussions
    about: Discuss things that may be outside the scope of our GitHub issue templates.
